# Generated by Django 5.0.1 on 2024-01-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0002_phone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
    ]
